import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';

test('real SQL: permissions, reservations, cancellation, handover, return and repair',async()=>{
 const db=new PGlite();
 await db.exec(`create role anon; create role authenticated; create role service_role;
 create table public.members(id text primary key,full_name text,display_name text,role text,membership_status text);
 insert into public.members values ('admin','เจ้าหน้าที่','','admin','active'),('alice','สมาชิกหนึ่ง','','member','active'),('bob','สมาชิกสอง','','member','active'),('blocked','ระงับ','','member','suspended');`);
 await db.exec(await readFile(new URL('../schema.sql',import.meta.url),'utf8'));
 const q=async(sql,p=[])=>(await db.query(sql,p)).rows;
 const item=(await q(`insert into public.gears_items(name,category_id) values ('สว่าน','tools') returning id`))[0].id;
 await q(`select public.gears_receive($1,'admin',2,'ชั้น A1','')`,[item]);
 const reserve=async(actor,qty)=>(await q(`select public.gears_reserve($1,$2::jsonb,'0812345678','ซ่อมศาลา',(now() at time zone 'Asia/Bangkok')::date+7,'2026-09-27') as loan`,[actor,JSON.stringify([{itemId:item,quantity:qty}])]))[0].loan;
 await assert.rejects(()=>reserve('blocked',1),/ไม่มีสิทธิ์/);
 const first=await reserve('alice',2);
 await assert.rejects(()=>reserve('bob',1),/จำนวนพร้อมให้ยืมไม่พอ/);
 assert.equal((await q('select count(*)::int as count from public.gears_loans'))[0].count,1,'failed reservation is fully rolled back');
 await assert.rejects(()=>q(`select public.gears_transition($1,'bob','cancel')`,[first.id]),/ไม่พบรายการ/);
 await assert.rejects(()=>q(`select public.gears_transition($1,'alice','approve')`,[first.id]),/เฉพาะเจ้าหน้าที่/);
 await q(`select public.gears_transition($1,'alice','cancel')`,[first.id]);
 assert.equal((await q(`select count(*)::int as count from public.gears_assets where status='available'`))[0].count,2);
 const loan=await reserve('bob',2);
 await assert.rejects(()=>q(`select public.gears_transition($1,'admin','accept_return')`,[loan.id]),/สถานะ/);
 await q(`select public.gears_transition($1,'admin','approve','',(now() at time zone 'Asia/Bangkok')::date+7)`,[loan.id]);
 await q(`select public.gears_transition($1,'admin','handover')`,[loan.id]);
 await assert.rejects(()=>q(`select public.gears_transition($1,'bob','cancel')`,[loan.id]),/สถานะ/);
 await q(`select public.gears_transition($1,'bob','request_return')`,[loan.id]);
 const assets=await q('select asset_id from public.gears_loan_items where loan_id=$1 order by asset_id',[loan.id]);
 await assert.rejects(()=>q(`select public.gears_asset_action($1,'admin','available','')`,[assets[0].asset_id]),/ต้องรับคืน/);
 await assert.rejects(()=>q(`select public.gears_transition($1,'admin','accept_return','','2027-01-01',$2::jsonb)`,[loan.id,JSON.stringify({[assets[0].asset_id]:'available'})]),/ทุกชิ้น/);
 assert.equal((await q(`select count(*)::int as count from public.gears_assets where status='on_loan'`))[0].count,2,'partial invalid return must roll back');
 const conditions={[assets[0].asset_id]:'available',[assets[1].asset_id]:'repair'};
 await q(`select public.gears_transition($1,'admin','accept_return','ตรวจครบ',null,$2::jsonb)`,[loan.id,JSON.stringify(conditions)]);
 assert.equal((await q('select status from public.gears_loans where id=$1',[loan.id]))[0].status,'returned');
 assert.equal((await q(`select count(*)::int as count from public.gears_loan_items where loan_id=$1 and active`,[loan.id]))[0].count,0);
 assert.equal((await q(`select count(*)::int as count from public.gears_assets where status='repair'`))[0].count,1);
 assert.equal((await q('select count(*)::int as count from public.gears_events where loan_id=$1',[loan.id]))[0].count,5);
 await db.exec('set role anon');
 await assert.rejects(()=>q('select * from public.gears_loans'),/permission denied/);
 await assert.rejects(()=>q(`select public.gears_transition($1,'admin','cancel')`,[loan.id]),/permission denied/);
 await db.close();
});
