const $=s=>document.querySelector(s);
const el=(tag,cls,value)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(value!=null)n.textContent=value;return n;};
const labels={pending:'รอเจ้าหน้าที่อนุมัติ',approved:'อนุมัติแล้ว · รอรับที่วัด',on_loan:'อยู่ระหว่างยืม',return_pending:'แจ้งนำมาคืน · รอตรวจรับ',returned:'คืนเรียบร้อย',rejected:'ไม่อนุมัติ',cancelled:'ยกเลิก',available:'พร้อมให้ยืม',reserved:'มีผู้จอง',repair:'พักซ่อม',retired:'สละออก'};
const terms='รับและคืนอุปกรณ์ด้วยตนเองที่วัดพุทธอุทยานนาเทิงเท่านั้น ผู้ยืมต้องดูแลอุปกรณ์ ใช้งานตามวัตถุประสงค์ คืนให้ครบตามกำหนด และแจ้งเจ้าหน้าที่เมื่อชำรุดหรือสูญหาย รายการจะสิ้นสุดเมื่อเจ้าหน้าที่ตรวจรับคืนเรียบร้อยแล้ว';
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const date=v=>v?new Date(v.length===10?v+'T12:00:00+07:00':v).toLocaleDateString('th-TH',{timeZone:'Asia/Bangkok',year:'numeric',month:'short',day:'numeric'}):'—';
const stamp=v=>new Date(v).toLocaleString('th-TH',{timeZone:'Asia/Bangkok',dateStyle:'medium',timeStyle:'short'});
const overdue=l=>['on_loan','return_pending'].includes(l.status)&&l.due_date<today();
let token='',expires=0,member=null,categories=[],inventory={items:[],assets:[]},cart=[],page=0,searchSeq=0,loanPage=0,adminPage=0,adminLoans=[];
let dialogSequence=0;
const button=(label,fn,cls='secondary')=>{const n=el('button',cls,label);n.type='button';n.onclick=async()=>{n.disabled=true;try{await fn();}catch(e){showError(e);}finally{n.disabled=false;}};return n;};
function showError(e,target){if(target){target.textContent=e.message;target.classList.add('error');if(e.status===401){const a=el('a','login-link','เข้าสู่ระบบสมาชิกวัด ↗');a.href='https://watt.nathoeng.com/#login-page';a.target='_blank';a.rel='noopener';target.append(a,document.createTextNode(' แล้วกลับมากดอัปเดต'));}}else{const box=$('#toast');box.textContent=e.message;box.hidden=false;setTimeout(()=>box.hidden=true,7000);}}
async function api(action,{method='GET',body,params={},auth=true}={}) {
 if(auth&&(!token||Date.now()>expires)){
  const r=await fetch('https://watt.nathoeng.com/api/line-login?route=gears-session',{credentials:'include',cache:'no-store'});
  if(!r.ok)throw Object.assign(Error(r.status===401?'กรุณาเข้าสู่ระบบด้วยบัญชีสมาชิกวัดเดิม':'ยังเชื่อมบัญชีสมาชิกไม่ได้ กรุณาตรวจการตั้งค่าเว็บวัด'),{status:r.status});
  token=(await r.json()).token;expires=Date.now()+120000;
 }
 const r=await fetch('/api/gears?'+new URLSearchParams({action,...params}),{method,cache:'no-store',headers:{...(auth?{Authorization:`Bearer ${token}`} :{}),...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});
 const data=await r.json().catch(()=>({error:'บริการยังไม่พร้อม กรุณาลองใหม่'}));
 if(!r.ok){if(r.status===401){token='';expires=0;}throw Object.assign(Error(data.error||'ไม่สามารถทำรายการได้'),{status:r.status});}return data;
}
async function me(){member=(await api('me')).member;return member;}
function openDialog(){dialogSequence++;$('#dialog-content').replaceChildren();if(!$('#dialog').open)$('#dialog').showModal();return $('#dialog-content');}
$('#close-dialog').onclick=()=>$('#dialog').close();
$('#dialog').addEventListener('close',()=>{dialogSequence++;});
function selectOptions(select,rows,blank){const value=select.value;select.replaceChildren();if(blank!=null)select.add(new Option(blank,''));for(const row of rows)select.add(new Option(row.name,row.id));select.value=value||select.options[0]?.value||'';}
async function loadCategories(){categories=(await api('categories',{auth:false})).categories;selectOptions($('#category'),categories,'ทุกหมวดหมู่');selectOptions($('#item-category'),categories);}
function picture(item){if(/^https:\/\//i.test(item.image_url||'')){const img=el('img','item-image');img.src=item.image_url;img.alt=item.name;img.loading='lazy';img.onerror=()=>img.replaceWith(el('div','placeholder','⌘'));return img;}return el('div','placeholder','⌘');}
async function search(append=false){const seq=++searchSeq;const status=$('#search-status');$('#search-results').hidden=false;status.textContent='กำลังค้นหา…';if(!append){page=0;$('#results').replaceChildren();}$('#more').hidden=true;try{const data=await api('catalog',{auth:false,params:{q:$('#search').value,category:$('#category').value,page}});if(seq!==searchSeq)return;status.textContent=data.items.length?'':(append?'ไม่มีรายการเพิ่มเติม':'ยังไม่พบอุปกรณ์ ลองเปลี่ยนคำค้นหรือหมวดหมู่');for(const item of data.items){const card=button('',()=>detail(item.id),'item-card');const body=el('div','card-body');body.append(el('small','',item.gears_categories?.name||''),el('h3','',item.name),el('span','badge'+(item.available?'':' grey'),`พร้อมให้ยืม ${item.available} / ${item.total} ${item.unit}`));card.append(picture(item),body);$('#results').append(card);}$('#more').hidden=!data.hasMore;}catch(e){showError(e,status);}}
$('#search-form').onsubmit=e=>{e.preventDefault();search();};$('#category').onchange=()=>search();$('#more').onclick=()=>{page++;search(true);};$('#clear-search').onclick=()=>{searchSeq++;$('#search').value='';$('#category').value='';$('#search-results').hidden=true;};
async function detail(id){const box=openDialog();const seq=dialogSequence;box.append(el('p','','กำลังเปิดรายละเอียด…'));try{const {item,assets}=await api('detail',{auth:false,params:{id}});if(seq!==dialogSequence)return;box.replaceChildren(el('small','',item.gears_categories?.name||''),el('h2','',item.name),picture(item),el('p','',item.description||'ยังไม่มีรายละเอียดเพิ่มเติม'));const available=assets.filter(a=>a.status==='available').length;box.append(el('span','badge',`พร้อมให้ยืม ${available} ${item.unit}`),el('p','muted','รับและคืนด้วยตนเองที่วัดเท่านั้น'));if(available){const form=el('form');const label=el('label','','จำนวนที่ต้องการยืม'),qty=el('input');qty.type='number';qty.min=1;qty.max=Math.min(available,50);qty.value=1;qty.required=true;label.append(qty);form.append(label);const add=el('button','','เพิ่มในรายการยืม');form.append(add);form.onsubmit=e=>{e.preventDefault();const existing=cart.find(x=>x.itemId===id);const amount=Number(qty.value)+(existing?.quantity||0);if(amount>Math.min(available,50))return showError(Error('จำนวนที่เลือกรวมเกินจำนวนพร้อมให้ยืม'));if(existing)existing.quantity=amount;else cart.push({itemId:id,name:item.name,unit:item.unit,quantity:amount});updateCart();$('#dialog').close();};box.append(form);}}catch(e){box.replaceChildren();showError(e,box);}}
function updateCart(){$('#cart-button').hidden=!cart.length;$('#cart-count').textContent=cart.reduce((n,x)=>n+x.quantity,0);}
$('#cart-button').onclick=async()=>{const box=openDialog();box.append(el('h2','','รายการขอยืม'));for(const item of cart){const row=el('div','cart-row');const qty=el('input');qty.type='number';qty.min=1;qty.max=50;qty.value=item.quantity;qty.setAttribute('aria-label','จำนวน '+item.name);qty.onchange=()=>{item.quantity=Math.min(50,Math.max(1,parseInt(qty.value)||1));qty.value=item.quantity;updateCart();};row.append(el('span','',item.name),qty,button('ลบ',()=>{cart=cart.filter(x=>x!==item);row.remove();updateCart();if(!cart.length)$('#dialog').close();},'ghost'));box.append(row);}const seq=dialogSequence;const state=el('p');box.append(state);try{await me();if(seq!==dialogSequence)return;state.textContent='ผู้ยืม: '+member.name;const f=el('form');const phone=field(f,'เบอร์โทรติดต่อ','phone','tel');phone.required=true;phone.maxLength=30;phone.pattern='[+0-9 ()-]{8,30}';const purpose=field(f,'วัตถุประสงค์การยืม','purpose');purpose.required=true;purpose.maxLength=1000;const due=field(f,'วันที่คาดว่าจะนำมาคืน','dueDate','date');due.required=true;due.min=today();f.append(el('p','terms',terms));const acceptLabel=el('label','check'),accept=el('input');accept.type='checkbox';accept.required=true;acceptLabel.append(accept,document.createTextNode('ข้าพเจ้ายอมรับเงื่อนไขการยืมและการคืนอุปกรณ์'));const submit=el('button','','ยืนยันส่งคำขอยืม');const status=el('p');status.setAttribute('role','status');f.append(acceptLabel,submit,status);f.onsubmit=async e=>{e.preventDefault();submit.disabled=true;try{const {loan}=await api('reserve',{method:'POST',body:{lines:cart.map(({itemId,quantity})=>({itemId,quantity})),phone:phone.value,purpose:purpose.value,dueDate:due.value,accepted:accept.checked,termsVersion:'2026-09-27'}});cart=[];updateCart();box.replaceChildren(el('h2','','ส่งคำขอยืมเรียบร้อย'),el('p','',`เลขรายการ ${loan.number}`),el('p','','รอเจ้าหน้าที่อนุมัติก่อนมารับอุปกรณ์ที่วัด'),button('ติดตามรายการ',()=>{$('#dialog').close();location.hash='loans';loadLoans();}));}catch(e){showError(e,status);submit.disabled=false;}};box.append(f);}catch(e){showError(e,state);}};
function field(parent,title,name,type='text',value=''){const label=el('label','',title),input=el('input');input.name=name;input.type=type;input.value=value;label.append(input);parent.append(label);return input;}
function loanCard(loan,staff=false){const card=el('article','loan-card'),top=el('div','loan-top');top.append(el('h3','',loan.number),el('span','badge'+(overdue(loan)?' red':loan.status==='pending'?' warn':''),overdue(loan)?'เกินกำหนดคืน':labels[loan.status]));card.append(top);if(staff)card.append(el('p','',`ผู้ยืม ${loan.borrower_name} · ${loan.phone}`));const names={};for(const line of loan.gears_loan_items||[])names[line.item_name]=(names[line.item_name]||0)+1;const list=el('ul','loan-items');for(const [name,count] of Object.entries(names))list.append(el('li','',`${name} × ${count}`));card.append(list,el('p','muted',`${labels[loan.status]} · กำหนดคืน ${date(loan.due_date)}`));const actions=el('div','actions');actions.append(button('รายละเอียด / ติดตาม',()=>viewLoan(loan.id)),button('พิมพ์ใบบันทึก',()=>printLoan(loan.id)));const add=(title,operation,cls)=>actions.append(button(title,()=>transitionForm(loan,operation,staff),cls));if(['pending','approved'].includes(loan.status))add('ยกเลิก','cancel','ghost');if(staff){if(loan.status==='pending'){add('อนุมัติ','approve','');add('ไม่อนุมัติ','reject','ghost');}if(loan.status==='approved')add('ส่งมอบที่วัด','handover','');if(['on_loan','return_pending'].includes(loan.status))add('ตรวจรับคืน','accept_return','');}else if(loan.status==='on_loan')add('แจ้งนำมาคืน','request_return','');card.append(actions);return card;}
async function loadLoans(append=false){const status=$('#member-state');status.classList.remove('error');status.textContent='กำลังเชื่อมบัญชีสมาชิกวัด…';$('#more-loans').hidden=true;if(!append){loanPage=0;$('#loan-list').replaceChildren();}try{await me();status.textContent=`${member.name} · ใช้บัญชีสมาชิกวัดเดิม`;const data=await api('loans',{params:{page:loanPage}});for(const loan of data.loans)$('#loan-list').append(loanCard(loan));if(!append&&!data.loans.length)$('#loan-list').append(el('p','empty','ยังไม่มีรายการยืม ค้นหาอุปกรณ์แล้วส่งคำขอได้เลย'));$('#more-loans').hidden=!data.hasMore;}catch(e){showError(e,status);}}
$('#refresh-loans').onclick=()=>loadLoans();$('#more-loans').onclick=()=>{loanPage++;loadLoans(true);};
async function viewLoan(id){const box=openDialog(),seq=dialogSequence;box.append(el('p','','กำลังโหลด…'));try{const {loan,events}=await api('loan',{params:{id}});if(seq!==dialogSequence)return;box.replaceChildren(el('h2','',loan.number),el('span','badge',labels[loan.status]),el('p','',`ผู้ยืม ${loan.borrower_name} · ${loan.phone}`),el('p','',`วัตถุประสงค์: ${loan.purpose}`),el('p','',`กำหนดคืน: ${date(loan.due_date)}`));const list=el('ul','loan-items');for(const l of loan.gears_loan_items)list.append(el('li','',`${l.asset_code} · ${l.item_name}${l.return_condition?' · '+labels[l.return_condition]:''}`));box.append(list,el('h3','','ประวัติติดตามรายการ'));const timeline=el('div','timeline');for(const event of events){const node=el('div','event');node.append(el('strong','',labels[event.action]||event.action),el('small','',stamp(event.created_at)));if(event.note)node.append(el('p','',event.note));timeline.append(node);}box.append(timeline,button('พิมพ์ใบบันทึกรายการยืม',()=>printLoan(id)));}catch(e){box.replaceChildren();showError(e,box);}}
async function transitionForm(loan,operation,staff){const box=openDialog();const names={approve:'อนุมัติคำขอ',reject:'ไม่อนุมัติคำขอ',cancel:'ยกเลิกรายการ',handover:'ยืนยันส่งมอบที่วัด',request_return:'แจ้งนำอุปกรณ์มาคืน',accept_return:'ตรวจรับคืนอุปกรณ์'};box.append(el('h2','',names[operation]),el('p','',`${loan.number} · ${loan.borrower_name}`));const f=el('form');let due;const conditions={};if(operation==='approve'){due=field(f,'กำหนดคืน','dueDate','date',loan.due_date);due.required=true;due.min=today();}if(operation==='accept_return'){f.append(el('p','terms','ตรวจนับอุปกรณ์ให้ครบทุกชิ้นก่อนยืนยัน หากยังคืนไม่ครบ ให้คงรายการไว้ก่อน'));for(const line of loan.gears_loan_items){const label=el('label','return-row',`${line.asset_code} · ${line.item_name}`),select=el('select');select.required=true;select.add(new Option('เลือกผลตรวจสภาพ',''));select.add(new Option('ครบและพร้อมให้ยืม','available'));select.add(new Option('ได้รับคืนแล้ว แต่ต้องพักซ่อม','repair'));conditions[line.asset_id]=select;label.append(select);f.append(label);}}if(operation==='handover')f.append(el('p','terms','ตรวจบัตรสมาชิกและส่งมอบของครบตามใบบันทึกแล้ว จึงกดยืนยัน'));if(operation==='request_return')f.append(el('p','terms','กรุณานำอุปกรณ์มาคืนที่วัด รายการยังอยู่ระหว่างยืมจนกว่าเจ้าหน้าที่จะตรวจรับ'));const note=field(f,'หมายเหตุ','note');note.maxLength=1000;if(operation==='reject')note.required=true;const confirm=el('label','check'),check=el('input');check.type='checkbox';check.required=true;confirm.append(check,document.createTextNode('ตรวจสอบข้อมูลแล้ว ยืนยันทำรายการ'));const submit=el('button','',names[operation]),state=el('p');state.setAttribute('role','status');f.append(confirm,submit,state);f.onsubmit=async e=>{e.preventDefault();submit.disabled=true;try{await api('transition',{method:'POST',body:{loanId:loan.id,operation,note:note.value,dueDate:due?.value,conditions:Object.fromEntries(Object.entries(conditions).map(([id,s])=>[id,s.value]))}});$('#dialog').close();if(staff)await loadAdmin();else await loadLoans();}catch(e){showError(e,state);submit.disabled=false;}};box.append(f);}
async function printLoan(id){const {loan}=await api('loan',{params:{id}});const area=$('#print-area');area.replaceChildren();const head=el('div','print-header'),brand=el('div');brand.append(el('h1','','ใบบันทึกรายการยืม–คืน'),el('p','','คลังเก็บของวัดพุทธอุทยานนาเทิง'),el('p','','231 หมู่ 2 บ้านตาลเดี่ยว ต.ธาตุ อ.วานรนิวาส จ.สกลนคร 47120'),el('p','','โทร. 0963513441 · gears.nathoeng.com'));head.append(brand,el('strong','',loan.number));const meta=el('div','print-meta');for(const line of [`ผู้ยืม: ${loan.borrower_name}`,`เบอร์โทร: ${loan.phone}`,`วันที่ทำรายการ: ${date(loan.requested_at)}`,`กำหนดคืน: ${date(loan.due_date)}`,`ส่งมอบเมื่อ: ${date(loan.handed_at)}`,`สถานะ: ${labels[loan.status]}`])meta.append(el('div','',line));area.append(head,meta,el('p','',`วัตถุประสงค์: ${loan.purpose}`));const table=el('table'),thead=el('thead'),tr=el('tr');for(const title of ['ลำดับ','รายการอุปกรณ์','รหัสประจำชิ้น','ผลตรวจรับคืน'])tr.append(el('th','',title));thead.append(tr);table.append(thead);const tbody=el('tbody');loan.gears_loan_items.forEach((line,i)=>{const row=el('tr');for(const cell of [i+1,line.item_name,line.asset_code,line.return_condition?labels[line.return_condition]:'________________'])row.append(el('td','',cell));tbody.append(row);});table.append(tbody);area.append(table,el('p','print-terms',terms));const signs=el('div','signatures');for(const title of ['ผู้ยืม / ผู้รับอุปกรณ์','เจ้าหน้าที่ผู้ส่งมอบ','เจ้าหน้าที่ผู้ตรวจรับคืน']){const sign=el('div');sign.append(el('p','','ลงชื่อ ____________________'),el('p','',title),el('p','','วันที่ ____ / ____ / ______'));signs.append(sign);}area.append(signs,el('p','print-foot',`รับและคืนที่วัดเท่านั้น · จำนวน ${loan.gears_loan_items.length} ชิ้น · พิมพ์เมื่อ ${stamp(new Date().toISOString())}`));window.print();}
async function loadAdmin(append=false){const status=$('#admin-state');status.classList.remove('error');status.textContent='กำลังตรวจสิทธิ์…';$('#admin-body').hidden=true;try{await me();if(!member.staff)throw Error('หน้านี้สำหรับเจ้าหน้าที่วัดที่มีสิทธิ์ผู้ดูแลระบบ');if(!append){adminPage=0;adminLoans=[];inventory=await api('inventory');if(!categories.length)await loadCategories();populateInventory();}const data=await api('loans',{params:{scope:'all',page:adminPage}});adminLoans.push(...data.loans);renderAdminLoans();$('#more-admin').hidden=!data.hasMore;$('#admin-body').hidden=false;status.textContent=`${member.name} · เจ้าหน้าที่คลังอุปกรณ์`;if(!document.querySelector('.tabs .active'))document.querySelector('[data-tab="requests"]').click();}catch(e){showError(e,status);}}
function renderAdminLoans(){const target=$('#admin-loans'),filter=$('#status-filter').value;target.replaceChildren();const shown=adminLoans.filter(l=>!filter||(filter==='overdue'?overdue(l):l.status===filter));for(const loan of shown)target.append(loanCard(loan,true));if(!shown.length)target.append(el('p','empty','ไม่มีรายการในข้อมูลที่โหลดแล้ว'));}
$('#status-filter').onchange=renderAdminLoans;$('#refresh-admin').onclick=()=>loadAdmin();$('#more-admin').onclick=()=>{adminPage++;loadAdmin(true);};
for(const tab of document.querySelectorAll('[data-tab]'))tab.onclick=()=>{for(const other of document.querySelectorAll('[data-tab]')){other.classList.toggle('active',other===tab);$('#'+other.dataset.tab).hidden=other!==tab;}};
function populateInventory(){selectOptions($('#edit-item'),inventory.items,'+ เพิ่มอุปกรณ์ใหม่');selectOptions($('#receive-item'),inventory.items.filter(i=>i.active),'เลือกอุปกรณ์');renderInventory();}
function renderInventory(){const target=$('#asset-list');target.replaceChildren();const q=$('#inventory-search').value.toLowerCase();const shown=inventory.assets.filter(a=>`${a.code} ${a.location} ${inventory.items.find(i=>i.id===a.item_id)?.name||''}`.toLowerCase().includes(q));$('#inventory-summary').textContent=`ทั้งหมด ${inventory.assets.length} ชิ้น · พร้อมให้ยืม ${inventory.assets.filter(a=>a.status==='available').length} · กำลังยืม ${inventory.assets.filter(a=>a.status==='on_loan').length} · พักซ่อม ${inventory.assets.filter(a=>a.status==='repair').length}`;for(const asset of shown){const row=el('div','asset-row'),label=el('div');label.append(el('strong','',inventory.items.find(i=>i.id===asset.item_id)?.name||'อุปกรณ์'),el('small','',`${asset.code} · ${asset.location||'ไม่ระบุจุดเก็บ'} · ${labels[asset.status]}`));row.append(label);if(['available','repair','retired'].includes(asset.status)){const select=el('select');select.setAttribute('aria-label','จัดการ '+asset.code);select.add(new Option('จัดการสถานะ',''));for(const status of ['available','repair','retired'])if(status!==asset.status)select.add(new Option(labels[status],status));select.onchange=async()=>{if(!select.value)return;const value=select.value;select.value='';const note=prompt(`ยืนยัน ${labels[value]}: ${asset.code}\nหมายเหตุ (กดยกเลิกเพื่อไม่เปลี่ยนสถานะ)`,'');if(note===null)return;select.disabled=true;try{await api('asset',{method:'POST',body:{assetId:asset.id,status:value,note}});asset.status=value;renderInventory();}catch(e){showError(e);}finally{select.disabled=false;}};row.append(select);}target.append(row);}if(!shown.length)target.append(el('p','empty','ยังไม่มีอุปกรณ์ เพิ่มข้อมูลและรับเข้าคลังเพื่อเริ่มใช้งาน'));}
$('#inventory-search').oninput=renderInventory;
$('#edit-item').onchange=()=>{const f=$('#item-form'),item=inventory.items.find(i=>i.id===f.elements.id.value);for(const [field,key] of [['name','name'],['categoryId','category_id'],['unit','unit'],['description','description'],['imageUrl','image_url']])f.elements[field].value=item?.[key]||(field==='unit'?'ชิ้น':field==='categoryId'?categories[0]?.id||'':'');f.elements.active.checked=item?item.active:true;};
function saveForm(id,action,transform,after){const f=$(id);f.onsubmit=async e=>{e.preventDefault();const button=f.querySelector('button[type="submit"]'),state=f.querySelector('.form-state');button.disabled=true;state.classList.remove('error');state.textContent='กำลังบันทึก…';try{const data=Object.fromEntries(new FormData(f));await api(action,{method:'POST',body:transform(data,f)});await after?.();state.textContent='บันทึกเรียบร้อย';}catch(e){showError(e,state);}finally{button.disabled=false;}};}
saveForm('#item-form','item',(d,f)=>({...d,active:f.elements.active.checked}),async()=>{inventory=await api('inventory');populateInventory();});
saveForm('#receive-form','receive',d=>({...d,quantity:Number(d.quantity)}),async()=>{inventory=await api('inventory');populateInventory();});
saveForm('#category-form','category',d=>d,async()=>{await loadCategories();$('#category-form').reset();});
async function route(){const name=['loans','admin'].includes(location.hash.slice(1))?location.hash.slice(1):'home';for(const id of ['home','loans','admin'])$('#'+id).hidden=id!==name;window.scrollTo(0,0);if(name==='loans')await loadLoans();if(name==='admin')await loadAdmin();}
window.addEventListener('hashchange',route);loadCategories().catch(()=>{});route();
